### ISSUE TITLE
Web Logo

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/saas-website#1]
I was trying to put my logo on the same row as my nav but it takes all the space in the row and pushes my nav to the next one. Wonder how can I fix it?

Thank you! 

@mackenzierose
@muxlowc
@hannahdelaney

**Comment by HannahDelaney** [comment]
Hey Anna!

You could try using `inline-block` on the units, or `display: flex` and other `flex` classes on the `grid` class to get them next to each other. Your grid css file doesn't seem to have any content yet though, so that won't help you see the results! ;)

**Comment by HannahDelaney** [comment]
Oh forgot to mention — you can't really put embed stuff at the same level as grids, in my experience that's going to mess things up. Maybe try using `img-flex` on the image, or add more `div`s to separate those class names.

Best of luck with the site!
